apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
    - name: mongodb-data #볼륨의 이름
      awsElasticBlockStore: #볼륨의 유형
        volumeId: <volume name> #여기 이름은 이전의 GCE PD와 일치해야 한다
        fsType: ext4 #리눅스 파일시스템중 하나
  containers:
    - image: mongo
      name: mongodb
      volumeMounts:
        - name: <volume name>
          mountPath: /data/db
      ports:
        - containerPort: 27017
          protocol: TCP
