apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: fast # PVC는 사용자 정의 스토리지 클래스를 요청한다.
  resources:
    requests:
      storage: 100Mi
    accessModes:
      - ReadWriteOnce